### PR TITLE
Add normal sdp exchange like js does.

### PR DESCRIPTION
**Pull request by SetoKaiba**
**UPDATE:** A more accurate description and keep it in English for foreign developers.

1. Add normal sdp exchange like js does.
2. Change the unity China version to unity Global version. Reason: The global version won't open because of the auto streaming package is missing in Global package registry. But it's not related.
3. Add NewtonSoft Json.Net to deserialize the json in threads.
4. Enable the SrsPlayerNormal, SrsPublisherNormal, SrsStreamerNormal to test.

Tested with ?codec=av1.

### CODE REVIEW

**Comment by SetoKaiba** [comment]
JZ{3~H~O T2TP}KP3Z92~IA
测试中，无论whip还是我的，都从后来看到有流，但是视频编码一栏是落空的，通过js正常推的流，是有h264什么的。

**Comment by SetoKaiba** [comment]
我看明白了那个streamer了，streamer是stream unity中的camera而不是现实的camera，我改一下再force push一下。另外我测试是用2022版本测试的，publish和stream都会有流但是无视频，我换到跟你一样的版本测试一下。

**Comment by winlinvip** [comment]
SRS defines two set of HTTP API:

1. Legacy API: `/rtc/v1/publish/`, we won't support it in future.
2. WHIP API: `/rtc/v1/whip/`, we will support it in future.

So please never use legacy API, and we will fix bugs if using WHIP api.

**Comment by SetoKaiba** [comment]
If the WHIP PR is merged. It would be ok.

**Comment by winlinvip** [comment]
Thanks, we will merge https://github.com/ossrs/srs/pull/3460/files#diff-2d94fb08a8b76aa40f71a392bb00afc19bb96767bd874cf74582a011488dc88cR641 today.

**Comment by SetoKaiba** [comment]
Hi, again. As the version 4 is still the intended stable version. Will this PR backport to it? Thank you.

**Pull request closed without merging**
